import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { parse as parseYaml } from 'yaml';

/**
 * Generate index.md if missing in docs dir.
 * Uses _index.yaml for structure or falls back to minimal homepage.
 */
export function generateIndexIfMissing(docsDir: string): void {
  const indexPath = join(docsDir, 'index.md');
  if (existsSync(indexPath)) return;

  const indexYamlPath = join(docsDir, '_index.yaml');
  let content: string;

  if (existsSync(indexYamlPath)) {
    content = generateFromIndexYaml(indexYamlPath);
  } else {
    content = generateMinimalIndex(docsDir);
  }

  writeFileSync(indexPath, content, 'utf8');
}

function generateFromIndexYaml(yamlPath: string): string {
  const raw = readFileSync(yamlPath, 'utf8');
  const manifest = parseYaml(raw) as {
    title?: string;
    description?: string;
    sections?: Array<{ title: string; path: string; description?: string }>;
  };

  const title = manifest?.title ?? 'Sekkei Documentation';
  const desc = manifest?.description ?? '';
  const lines: string[] = [
    '---',
    'layout: home',
    '---',
    '',
    `# ${title}`,
    '',
  ];

  if (desc) lines.push(desc, '');

  if (manifest?.sections?.length) {
    lines.push('## Documents', '');
    for (const section of manifest.sections) {
      const link = section.path.replace(/\.md$/, '');
      lines.push(`- [${section.title}](/${link})${section.description ? ` — ${section.description}` : ''}`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

function generateMinimalIndex(docsDir: string): string {
  // Try to get project name from sekkei.config.yaml
  let projectName = 'Sekkei Documentation';
  const configPath = join(process.cwd(), 'sekkei.config.yaml');
  if (existsSync(configPath)) {
    try {
      const raw = readFileSync(configPath, 'utf8');
      const config = parseYaml(raw) as { project?: { name?: string } };
      if (config?.project?.name) {
        projectName = config.project.name;
      }
    } catch {
      // ignore
    }
  }

  return [
    '---',
    'layout: home',
    '---',
    '',
    `# ${projectName}`,
    '',
    `Documentation generated by [Sekkei](https://github.com/bienhoang/sekkei).`,
    '',
  ].join('\n');
}
