/** Project-type instructions for domain types. Arch types (microservice/hybrid/event-driven/ai-ml) in project-type-instructions-arch.ts */
import type { DocType, ProjectType } from "../types/documents.js";
import { PROJECT_TYPE_INSTRUCTIONS_ARCH } from "./project-type-instructions-arch.js";

const PROJECT_TYPE_INSTRUCTIONS_BASE: Partial<Record<ProjectType, Partial<Record<DocType, string>>>> = {
  saas: {
    "basic-design": [
      "## Project Type: SaaS",
      "Include multi-tenant architecture section. Address:",
      "- Tenant isolation strategy (shared DB / DB per tenant / schema per tenant)",
      "- Billing integration points in API design",
      "- Subscription management screens (SCR-xxx for tenant admin)",
      "- Data partitioning in DB design (tenant_id foreign key pattern)",
      "",
      "### Additional: テナント分離設計",
      "- Tenant data isolation enforcement (row-level security / schema separation)",
      "- Tenant-specific customization points (white-label, custom fields, branding)",
      "- Cross-tenant data access controls and audit",
    ].join("\n"),
    "detail-design": [
      "## Project Type: SaaS Detail Design",
      "- Multi-tenant class design: TenantContext, TenantScopedRepository, TenantResolver",
      "- API pagination patterns: cursor-based for list endpoints, include tenant isolation in query layer",
      "- Subscription service classes: PlanManager, BillingAdapter, UsageMeter",
    ].join("\n"),
    requirements: "## Project Type: SaaS\nInclude SaaS-specific NFRs: multi-tenant data isolation, subscription tiers, API rate limiting, tenant provisioning SLA.",
    "security-design": [
      "## Project Type: SaaS Security",
      "### Tenant Isolation",
      "- Tenant-scoped API keys and token isolation",
      "- Data isolation strategy (row-level security / schema / DB per tenant)",
      "- Cross-tenant access prevention controls",
      "### API Security",
      "- Per-tenant rate limiting and quota management",
      "- API gateway authentication (OAuth2 + tenant context)",
      "- Webhook security (signature verification, replay protection)",
      "### Infrastructure",
      "- Shared infrastructure security boundaries",
      "- Secret management per tenant (key rotation, scoping)",
    ].join("\n"),
  },
  "internal-system": {
    "basic-design": [
      "## Project Type: Internal System",
      "Include migration design references (移行設計). Address:",
      "- AS-IS vs TO-BE comparison in system architecture (Section 2)",
      "- Legacy system interfaces in external interface (Section 8)",
      "- Data migration approach in DB design (Section 7)",
      "- Parallel run period design if applicable",
      "",
      "### Additional: 移行戦略 (Migration Strategy)",
      "- Migration phases and timeline",
      "- Data migration plan per table (mapping, transformation rules)",
      "- API compatibility matrix (old endpoints → new endpoints)",
      "- Rollback triggers and procedures",
    ].join("\n"),
    requirements: "## Project Type: Internal System\nInclude operational requirements: batch schedule, help desk SLA, training plan. Add migration-specific requirements if system replacement.",
    "security-design": [
      "## Project Type: Internal System Security",
      "- Active Directory / LDAP integration for authentication",
      "- Internal network zone security (DMZ, trusted zone, restricted zone)",
      "- VPN access requirements for remote users",
      "- Legacy system integration security (API compatibility, data sanitization)",
    ].join("\n"),
    "detail-design": [
      "## Project Type: Internal System Detail Design",
      "- Migration-aware class design: LegacyAdapter, DataMigrationService, ParallelRunManager",
      "- Batch integration classes: ScheduledJobExecutor, FileImporter, LegacyFileParser",
      "- AD/LDAP integration: LdapAuthProvider, GroupSyncService, RoleMapper",
    ].join("\n"),
  },
  mobile: {
    "detail-design": [
      "## Project Type: Mobile Detail Design",
      "- ViewModel/Repository pattern: ScreenViewModel, DataRepository, RemoteDataSource, LocalDataSource",
      "- Offline sync classes: SyncManager, ConflictResolver, OfflineQueueProcessor",
      "- Platform-specific adapters: abstract interfaces with iOS/Android concrete implementations",
    ].join("\n"),
    "basic-design": [
      "## Project Type: Mobile",
      "Include screen transition diagram for ALL screens.",
      "- Push notification spec in external interface",
      "- OS version support matrix (iOS/Android minimum versions)",
      "- Offline mode behavior per screen if applicable",
      "- App lifecycle events (background/foreground) affecting data sync",
    ].join("\n"),
    "security-design": [
      "## Project Type: Mobile Security",
      "- Certificate pinning for API communication",
      "- Secure local storage (Keychain/Keystore)",
      "- Biometric authentication integration",
      "- Jailbreak/root detection strategy",
      "- OAuth2 + PKCE flow for mobile clients",
      "- Offline data encryption",
      "- Screenshot/screen recording prevention for sensitive screens",
    ].join("\n"),
    requirements: [
      "## Project Type: Mobile",
      "Include mobile-specific requirements: supported OS versions (iOS/Android minimum),",
      "device categories (phone/tablet), push notification requirements.",
      "Add offline mode requirements: sync strategy, conflict resolution, local storage limits.",
      "Define app distribution: App Store/Play Store guidelines, enterprise distribution if applicable.",
    ].join("\n"),
  },
  batch: {
    "basic-design": [
      "## Project Type: Batch",
      "Include ジョブスケジュール table: job-ID, trigger, frequency, dependency, timeout, retry policy.",
      "- Job dependency chain visualization (Mermaid flowchart: Job A → Job B → Job C)",
      "- Error recovery strategy per job type (retry/skip/manual intervention)",
      "- Data volume estimation per batch (ピーク時データ量 column in TBL table)",
      "- Monitoring & alerting thresholds for batch failures",
    ].join("\n"),
    "detail-design": "## Project Type: Batch\nFor each batch process: input/output file specs, error handling procedure, restart procedure, estimated execution time.",
    "security-design": [
      "## Project Type: Batch Security",
      "- Batch job execution identity (service account, least privilege)",
      "- Input file validation and sanitization before processing",
      "- Temporary file cleanup and secure deletion after job completion",
      "- Encrypted data transfer for batch input/output files",
      "- Job execution audit logging (start, end, records processed, errors)",
    ].join("\n"),
    requirements: [
      "## Project Type: Batch",
      "Include batch-specific requirements: job scheduling constraints, data volume estimates per job.",
      "Add operational requirements: monitoring thresholds, alerting rules, restart/recovery procedures.",
      "Define file I/O requirements: input sources, output destinations, encoding, delimiter formats.",
    ].join("\n"),
  },
  lp: {
    "basic-design": "## Project Type: Landing Page\nFocus on: page structure, conversion funnel, form spec, analytics/tracking integration.",
    requirements: "## Project Type: Landing Page\nScope to: conversion goals, A/B test requirements, SEO constraints, analytics/tracking requirements, form validation rules, third-party integration (CRM, MA tools).",
    "detail-design": [
      "## Project Type: Landing Page Detail Design",
      "- Component classes: HeroSection, CTAButton, FormValidator, AnalyticsTracker",
      "- A/B test framework: VariantRenderer, ExperimentManager, ConversionTracker",
      "- Third-party integration: CRMAdapter, MarketingAutomationBridge, TagManagerService",
    ].join("\n"),
    "security-design": [
      "## Project Type: Landing Page Security",
      "- Form input validation and XSS prevention for all user-submitted fields",
      "- CSRF protection for form submissions",
      "- Third-party script CSP (Content Security Policy) configuration",
      "- Privacy compliance: cookie consent, tracking opt-out, GDPR/個人情報保護法",
    ].join("\n"),
  },
  government: {
    "detail-design": [
      "## Project Type: Government Detail Design",
      "- Audit trail classes: AuditLogger, AuditEventBuilder, AuditQueryService (full CRUD audit)",
      "- PII handling: PIIClassifier, DataMaskingService, ConsentValidator",
      "- Accessibility: AccessibilityValidator, WCAG2.1-AA compliance checker per screen component",
    ].join("\n"),
    "basic-design": [
      "## Project Type: Government",
      "Include accessibility design (WCAG 2.1 AA) for all screens.",
      "- Audit trail design section (who did what, when)",
      "- Data retention policy per table in DB design",
      "- PII (個人情報) marking on fields/tables",
      "- Digital Agency (デジタル庁) guideline compliance notes",
    ].join("\n"),
    requirements: "## Project Type: Government\n法令要件セクションを追加: デジタル庁ガイドライン準拠, 監査要件, 政府セキュリティ要件を含めること",
    "security-design": [
      "## Project Type: Government Security",
      "- Data sovereignty requirements (国内データ保管義務)",
      "- 個人情報保護法 detailed compliance matrix",
      "- Security clearance level mapping to data access",
      "- Full audit trail for all data operations (retention: minimum 5 years)",
      "- Tamper-evident logging (hash chain or WORM)",
      "- PII data flow diagram mandatory",
      "- Privacy Impact Assessment (PIA) reference",
    ].join("\n"),
  },
  finance: {
    "detail-design": [
      "## Project Type: Finance Detail Design",
      "- Transaction classes: TransactionProcessor, IdempotencyKeyManager, DoubleEntryLedger",
      "- Audit decorators: @Auditable on all financial operations, AuditTrailService",
      "- Reconciliation: ReconciliationEngine, DiscrepancyReporter, SettlementCalculator",
    ].join("\n"),
    "basic-design": [
      "## Project Type: Finance",
      "Include transaction integrity design.",
      "- FISC安全対策基準 compliance in security design section",
      "- Audit logging for all financial transactions",
      "- Data encryption at rest for sensitive financial data",
    ].join("\n"),
    requirements: "## Project Type: Finance\n金融庁ガイドライン, FISC安全対策基準への準拠を明記. 取引記録保存要件セクションを追加",
    "security-design": [
      "## Project Type: Finance Security",
      "- FISC安全対策基準 compliance mapping per SEC entry",
      "- PCI-DSS requirements if handling card data",
      "- Transaction integrity: idempotency, double-spend prevention",
      "- Real-time fraud detection integration points",
      "- HSM usage for cryptographic key storage",
      "- Key rotation schedule (quarterly for data keys, annually for master keys)",
    ].join("\n"),
  },
  healthcare: {
    "detail-design": [
      "## Project Type: Healthcare Detail Design",
      "- FHIR resource mappers: FHIRPatientMapper, FHIRObservationMapper, BundleBuilder",
      "- Consent management: ConsentService, ConsentPolicyEngine, AccessDecisionManager",
      "- HL7 adapters: HL7MessageParser, HL7MessageBuilder, IntegrationBridge",
    ].join("\n"),
    "basic-design": [
      "## Project Type: Healthcare",
      "Include HL7/FHIR interface design in external interface section.",
      "- Patient data protection (3省2ガイドライン準拠)",
      "- Medical device integration specs if applicable",
      "- Consent management screens",
    ].join("\n"),
    requirements: "## Project Type: Healthcare\n医療情報ガイドライン参照. HL7/FHIR連携要件を検討. 個人情報保護（医療特則）セクションを追加",
    "security-design": [
      "## Project Type: Healthcare Security",
      "- 3省2ガイドライン (厚労省・経産省・総務省) compliance matrix",
      "- PHI (Protected Health Information) handling procedures",
      "- Consent management design for patient data access",
      "- Medical record encryption (at rest and in transit)",
      "- Emergency access override (break-glass) procedures",
    ].join("\n"),
  },
};

export const PROJECT_TYPE_INSTRUCTIONS: Partial<Record<ProjectType, Partial<Record<DocType, string>>>> = {
  ...PROJECT_TYPE_INSTRUCTIONS_BASE,
  ...PROJECT_TYPE_INSTRUCTIONS_ARCH,
};
